# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build with prefix ${{ matrix.prefix }}
    strategy:
      matrix: 
        prefix: ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
      - uses: actions/checkout@v4

      - name: Checkout CCI
        uses: actions/checkout@v4
        with:
          repository: conan-io/conan-center-index
          path: conan-center-index

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip' # caching pip dependencies
      - run: |
          python3 -m pip install -r requirements.txt
        
      - name: Scan libc symbols
        working-directory: conan-center-index/recipes
        run: ../../scan.sh ${{ matrix.prefix }}